version: "3"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: indexer-user
      POSTGRES_DB: indexer-db
      POSTGRES_PASSWORD: indexer-password
    ports:
      - "5432:5432"

  migrations:
    image: "gol2-migrations"
    build:
      context: .
      dockerfile: Dockerfile
      target: migrations
    depends_on:
      db:
        condition: service_started
        required: true
    env_file:
      - .env
      - .env.docker

  indexer:
    image: "gol2-indexer"
    build:
      context: .
      dockerfile: Dockerfile
      target: indexer
    depends_on:
      db:
        condition: service_started
        required: true
      migrations:
        condition: service_completed_successfully
        required: true
    env_file:
      - .env
      - .env.docker

  web:
    image: "gol2-web"
    build:
      context: .
      dockerfile: Dockerfile
      target: web
    depends_on:
      db:
        condition: service_started
        required: true
      migrations:
        condition: service_completed_successfully
        required: true
    env_file:
      - .env
      - .env.docker
    ports:
      - "3000:3000"

  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    environment:
      DOZZLE_ENABLE_ACTIONS: true
      DOZZLE_NO_ANALYTICS: true

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: cotne.95@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_started
        required: true
