version: "3"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: indexer-user
      POSTGRES_DB: indexer-db
      POSTGRES_PASSWORD: indexer-password
    volumes:
      - ./apps/indexer/db/schema.sql:/docker-entrypoint-initdb.d/0-schema.sql
    ports:
      - "5432:5432"
  indexer:
    build: .
    depends_on:
      - db
    env_file:
      - .env
      - .env.docker
