FROM alpine:latest as node
RUN apk add nodejs

FROM node as src
WORKDIR /src

ENV CI=true

RUN apk add npm
RUN npm install -g corepack
RUN corepack enable

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps/web/package.json ./apps/web/

RUN pnpm install

COPY apps/web/public ./apps/web/public/
COPY apps/web/app ./apps/web/app/
COPY apps/web/postcss.config.js ./apps/web/
COPY apps/web/tailwind.config.js ./apps/web/
COPY apps/web/tsconfig.json ./apps/web/
COPY apps/web/vite.config.ts ./apps/web/
COPY tsconfig.options.json tsconfig.projects.json ./

RUN pnpm run --filter=./apps/web build
RUN pnpm deploy --filter=./apps/web --prod /app

FROM node as app
WORKDIR /app

COPY --from=src /app/package.json ./
COPY --from=src /app/build ./build
COPY --from=src /app/node_modules ./node_modules

EXPOSE 3000

CMD ["./node_modules/.bin/remix-serve", "./build/server/index.js"]
