version: '3'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: indexer-user
      POSTGRES_DB: indexer-db
      POSTGRES_PASSWORD: indexer-password
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/0-schema.sql
      - ./db/init-materialized-views.sql:/docker-entrypoint-initdb.d/1-init-materialized-views.sql
    ports:
      - "5432:5432"
  indexer:
    build: .
    depends_on:
      - db
    env_file: .env
    environment:
      DATABASE_URL: postgres://indexer-user:indexer-password@db/indexer-db?sslmode=disable
