version: "3"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: indexer-user
      POSTGRES_DB: indexer-db
      POSTGRES_PASSWORD: indexer-password
    ports:
      - "5432:5432"

  migrations:
    image: "gol2-migrations"
    build:
      context: .
      dockerfile: Dockerfile
      target: migrations
    depends_on:
      db:
        condition: service_started
        required: true
    env_file:
      - .env
      - .env.docker

  indexer:
    image: "gol2-indexer"
    build:
      context: .
      dockerfile: Dockerfile
      target: indexer
    depends_on:
      db:
        condition: service_started
        required: true
      migrations:
        condition: service_completed_successfully
        required: true
    env_file:
      - .env
      - .env.docker

  web:
    image: "gol2-web"
    build:
      context: .
      dockerfile: Dockerfile
      target: web
    depends_on:
      db:
        condition: service_started
        required: true
      migrations:
        condition: service_completed_successfully
        required: true
    env_file:
      - .env
      - .env.docker
    ports:
      - "3000:3000"
