FROM ghcr.io/amacneil/dbmate as dbmate

FROM alpine:latest as migrations

RUN apk add --no-cache postgresql-client tzdata

COPY --from=dbmate /usr/local/bin/dbmate /usr/local/bin/dbmate

WORKDIR /app
COPY db ./db/

ENV DBMATE_NO_DUMP_SCHEMA=true
ENTRYPOINT ["/usr/local/bin/dbmate"]
CMD ["--wait", "up"]
