version: "3"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: indexer-user
      POSTGRES_DB: indexer-db
      POSTGRES_PASSWORD: indexer-password
    volumes:
      - ./apps/indexer/db/schema.sql:/docker-entrypoint-initdb.d/0-schema.sql
    ports:
      - "5432:5432"
  indexer:
    image: "gol2-indexer"
    build:
      context: .
      dockerfile: Dockerfile.indexer
    depends_on:
      - db
    env_file:
      - .env
      - .env.docker
  web:
    image: "gol2-web"
    build:
      context: .
      dockerfile: Dockerfile.web
    depends_on:
      - db
    env_file:
      - .env
      - .env.docker
    ports:
      - "3000:3000"
