// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type ColumnType, type Selectable } from 'kysely';

/** Represents the materializedView public.balance */
export default interface BalanceTable {
  userId: ColumnType<string | null, never, never>;

  balance: ColumnType<string | null, never, never>;

  createdAt: ColumnType<Date | null, never, never>;

  updatedAt: ColumnType<Date | null, never, never>;
}

export type Balance = Selectable<BalanceTable>;
