// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the materializedView public.balance */
export default interface Balance {
  userId: string | null;

  balance: string | null;

  createdAt: Date | null;

  updatedAt: Date | null;
}
