// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type EventTransactionHash, type EventEventIndex } from './Event';
import { type ColumnType, type Selectable } from 'kysely';

/** Represents the view public.balance_events */
export default interface BalanceEventsTable {
  userId: ColumnType<string, never, never>;

  balance: ColumnType<string, never, never>;

  blockHash: ColumnType<string, never, never>;

  blockIndex: ColumnType<number, never, never>;

  transactionHash: ColumnType<EventTransactionHash, never, never>;

  transactionIndex: ColumnType<number, never, never>;

  eventIndex: ColumnType<EventEventIndex, never, never>;

  createdAt: ColumnType<Date, never, never>;

  updatedAt: ColumnType<Date, never, never>;
}

export type BalanceEvents = Selectable<BalanceEventsTable>;
