// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type ColumnType, type Selectable } from 'kysely';

/** Represents the view public.balance */
export default interface BalanceTable {
  userId: ColumnType<string, never, never>;

  balance: ColumnType<string, never, never>;
}

export type Balance = Selectable<BalanceTable>;
