// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the materializedView public.creator */
export default interface Creator {
  transactionHash: string | null;

  transactionType: string | null;

  eventIndex: number | null;

  transactionOwner: string | null;

  gameId: string | null;

  gameGeneration: string | null;

  gameState: string | null;

  gameOver: boolean | null;

  createdAt: Date | null;
}
