// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type ColumnType, type Selectable } from 'kysely';

/** Represents the materializedView public.creator */
export default interface CreatorTable {
  transactionHash: ColumnType<string | null, never, never>;

  transactionType: ColumnType<string | null, never, never>;

  txFinalityStatus: ColumnType<string | null, never, never>;

  txExecutionStatus: ColumnType<string | null, never, never>;

  eventIndex: ColumnType<number | null, never, never>;

  transactionOwner: ColumnType<string | null, never, never>;

  gameId: ColumnType<string | null, never, never>;

  gameGeneration: ColumnType<string | null, never, never>;

  gameState: ColumnType<string | null, never, never>;

  gameOver: ColumnType<boolean | null, never, never>;

  createdAt: ColumnType<Date | null, never, never>;
}

export type Creator = Selectable<CreatorTable>;
