// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';

/** Identifier type for public.event */
export type EventTxHash = string & { __brand: 'EventTxHash' };

/** Identifier type for public.event */
export type EventEventIndex = number & { __brand: 'EventEventIndex' };

/** Represents the table public.event */
export default interface EventTable {
  txHash: ColumnType<EventTxHash, EventTxHash, EventTxHash>;

  eventIndex: ColumnType<EventEventIndex, EventEventIndex, EventEventIndex>;

  txFinalityStatus: ColumnType<string, string, string>;

  txExecutionStatus: ColumnType<string | null, string | null, string | null>;

  txIndex: ColumnType<number, number, number>;

  blockHash: ColumnType<string | null, string | null, string | null>;

  blockIndex: ColumnType<number | null, number | null, number | null>;

  name: ColumnType<string, string, string>;

  content: ColumnType<unknown, unknown, unknown>;

  createdAt: ColumnType<Date, Date | string | undefined, Date | string>;

  updatedAt: ColumnType<Date | null, Date | string | null, Date | string | null>;
}

export type Event = Selectable<EventTable>;

export type NewEvent = Insertable<EventTable>;

export type EventUpdate = Updateable<EventTable>;
