// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type ColumnType, type Selectable } from 'kysely';

/** Represents the view public.game_state */
export default interface GameStateTable {
  gameId: ColumnType<string, never, never>;

  gameGeneration: ColumnType<string, never, never>;

  gameState: ColumnType<string, never, never>;

  gameOver: ColumnType<boolean, never, never>;

  revivedCells: ColumnType<unknown, never, never>;
}

export type GameState = Selectable<GameStateTable>;
