// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type EventTransactionHash, type EventEventIndex } from './Event';
import { type ColumnType, type Selectable } from 'kysely';

/** Represents the view public.game_events */
export default interface GameEventsTable {
  blockHash: ColumnType<string | null, never, never>;

  blockIndex: ColumnType<number | null, never, never>;

  transactionHash: ColumnType<EventTransactionHash, never, never>;

  transactionIndex: ColumnType<number, never, never>;

  transactionOwner: ColumnType<string, never, never>;

  transactionStatus: ColumnType<string, never, never>;

  eventIndex: ColumnType<EventEventIndex, never, never>;

  eventName: ColumnType<string, never, never>;

  eventData: ColumnType<unknown, never, never>;

  createdAt: ColumnType<Date, never, never>;

  updatedAt: ColumnType<Date, never, never>;

  gameId: ColumnType<string, never, never>;

  gameGeneration: ColumnType<string, never, never>;

  gameState: ColumnType<string, never, never>;

  revivedCellIndex: ColumnType<string, never, never>;

  gameOver: ColumnType<boolean, never, never>;
}

export type GameEvents = Selectable<GameEventsTable>;
