// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the materializedView public.infinite */
export default interface Infinite {
  transactionHash: string | null;

  transactionType: string | null;

  eventIndex: number | null;

  transactionOwner: string | null;

  gameGeneration: string | null;

  gameState: string | null;

  revivedCellIndex: string | null;

  gameExtinct: boolean | null;

  createdAt: Date | null;
}
