// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type ColumnType, type Selectable } from 'kysely';

/** Represents the materializedView public.infinite */
export default interface InfiniteTable {
  transactionHash: ColumnType<string | null, never, never>;

  transactionType: ColumnType<string | null, never, never>;

  eventIndex: ColumnType<number | null, never, never>;

  transactionOwner: ColumnType<string | null, never, never>;

  gameGeneration: ColumnType<string | null, never, never>;

  gameState: ColumnType<string | null, never, never>;

  revivedCellIndex: ColumnType<string | null, never, never>;

  txStatus: ColumnType<string | null, never, never>;

  gameExtinct: ColumnType<boolean | null, never, never>;

  createdAt: ColumnType<Date | null, never, never>;
}

export type Infinite = Selectable<InfiniteTable>;
