// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type default as SchemaMigrationsTable } from './SchemaMigrations';
import { type default as EventTable } from './Event';
import { type default as TransactionTable } from './Transaction';
import { type default as BalanceTable } from './Balance';
import { type default as CreatorTable } from './Creator';
import { type default as InfiniteTable } from './Infinite';

export default interface PublicSchema {
  schema_migrations: SchemaMigrationsTable;

  event: EventTable;

  transaction: TransactionTable;

  balance: BalanceTable;

  creator: CreatorTable;

  infinite: InfiniteTable;
}
