// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.schema_migrations */
export type SchemaMigrationsVersion = string & { __brand: 'SchemaMigrationsVersion' };

/** Represents the table public.schema_migrations */
export default interface SchemaMigrations {
  version: SchemaMigrationsVersion;
}

/** Represents the initializer for the table public.schema_migrations */
export interface SchemaMigrationsInitializer {
  version: SchemaMigrationsVersion;
}

/** Represents the mutator for the table public.schema_migrations */
export interface SchemaMigrationsMutator {
  version?: SchemaMigrationsVersion;
}
