// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type EventTransactionHash, type EventEventIndex } from './Event';
import { type ColumnType, type Selectable } from 'kysely';

/** Represents the view public.transfer_events */
export default interface TransferEventsTable {
  transferFrom: ColumnType<string, never, never>;

  transferTo: ColumnType<string, never, never>;

  transferAmount: ColumnType<string, never, never>;

  blockHash: ColumnType<string | null, never, never>;

  blockIndex: ColumnType<number | null, never, never>;

  transactionHash: ColumnType<EventTransactionHash, never, never>;

  transactionIndex: ColumnType<number, never, never>;

  eventIndex: ColumnType<EventEventIndex, never, never>;

  createdAt: ColumnType<Date, never, never>;

  updatedAt: ColumnType<Date, never, never>;
}

export type TransferEvents = Selectable<TransferEventsTable>;
