// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { Knex } from 'knex';
import { type SchemaMigrationsInitializer, type SchemaMigrationsMutator, type default as SchemaMigrations } from './public/SchemaMigrations';
import { type EventInitializer, type EventMutator, type default as Event } from './public/Event';
import { type TransactionInitializer, type TransactionMutator, type default as Transaction } from './public/Transaction';
import { type default as Balance } from './public/Balance';
import { type default as Creator } from './public/Creator';
import { type default as Infinite } from './public/Infinite';

declare module 'knex/types/tables' {
  interface Tables {
    'schema_migrations': Knex.CompositeTableType<SchemaMigrations, SchemaMigrationsInitializer, SchemaMigrationsMutator>;
    'event': Knex.CompositeTableType<Event, EventInitializer, EventMutator>;
    'transaction': Knex.CompositeTableType<Transaction, TransactionInitializer, TransactionMutator>;
    'balance': Knex.CompositeTableType<Balance, never, never>;
    'creator': Knex.CompositeTableType<Creator, never, never>;
    'infinite': Knex.CompositeTableType<Infinite, never, never>;
  }
}
