// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type EventNetworkName, type EventContractAddress, type EventEventIndex } from './Event';
import { type ColumnType, type Selectable } from 'kysely';

/** Represents the view public.game */
export default interface GameTable {
  networkName: ColumnType<EventNetworkName, never, never>;

  contractAddress: ColumnType<EventContractAddress, never, never>;

  gameId: ColumnType<string | null, never, never>;

  gameOwner: ColumnType<string | null, never, never>;

  gameGeneration: ColumnType<string, never, never>;

  gameState: ColumnType<string, never, never>;

  gameOver: ColumnType<boolean, never, never>;

  blockIndex: ColumnType<number, never, never>;

  transactionIndex: ColumnType<number, never, never>;

  eventIndex: ColumnType<EventEventIndex, never, never>;

  revivedCellIndexes: ColumnType<string[], never, never>;

  revivedCellOwners: ColumnType<string[], never, never>;
}

export type Game = Selectable<GameTable>;
