// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type default as EventTable } from './Event';
import { type default as SchemaMigrationsTable } from './SchemaMigrations';
import { type default as BalanceTable } from './Balance';
import { type default as GameCurrentGenerationTable } from './GameCurrentGeneration';
import { type default as GameRevivedCellsTable } from './GameRevivedCells';
import { type default as GameStateTable } from './GameState';
import { type default as GameTable } from './Game';
import { type default as GameEventTable } from './GameEvent';

export default interface PublicSchema {
  event: EventTable;

  schema_migrations: SchemaMigrationsTable;

  balance: BalanceTable;

  game_current_generation: GameCurrentGenerationTable;

  game_revived_cells: GameRevivedCellsTable;

  game_state: GameStateTable;

  game: GameTable;

  game_event: GameEventTable;
}
